/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    public Vista1() {
        initComponents();
        this.setTitle("PROGRAMACION-TRADUCCION CLAVE MURCIELAGO");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_texto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lbl_longitud = new javax.swing.JLabel();
        lbl_totalpalabras = new javax.swing.JLabel();
        lbl_primerletra = new javax.swing.JLabel();
        lbl_ultimaletra = new javax.swing.JLabel();
        lbl_letracentro = new javax.swing.JLabel();
        lbl_primerpalabra = new javax.swing.JLabel();
        lbl_palabracentral = new javax.swing.JLabel();
        lbl_ultimapalabra = new javax.swing.JLabel();
        lbl_repeticionesA = new javax.swing.JLabel();
        lbl_repeticionesE = new javax.swing.JLabel();
        lbl_repeticionesI = new javax.swing.JLabel();
        lbl_repeticionesO = new javax.swing.JLabel();
        lbl_repeticionesU = new javax.swing.JLabel();
        lbl_palabrapar = new javax.swing.JLabel();
        lbl_palabraimpar = new javax.swing.JLabel();
        txt_longitud = new javax.swing.JTextField();
        txt_totalpalabras = new javax.swing.JTextField();
        txt_primerletra = new javax.swing.JTextField();
        txt_ultimaletra = new javax.swing.JTextField();
        txt_letracentral = new javax.swing.JTextField();
        txt_primerpalabra = new javax.swing.JTextField();
        txt_palabracentral = new javax.swing.JTextField();
        txt_ultimapalabra = new javax.swing.JTextField();
        txt_repeticionesA = new javax.swing.JTextField();
        txt_repeticionesE = new javax.swing.JTextField();
        txt_repeticionesI = new javax.swing.JTextField();
        txt_repetiionesO = new javax.swing.JTextField();
        txt_repeticionesU = new javax.swing.JTextField();
        txt_palabrapar = new javax.swing.JTextField();
        txt_palabraimpar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_traduccionMurcielago = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setText("Manejo de cadenas ");
        jLabel1.setToolTipText("");

        txt_texto.setColumns(20);
        txt_texto.setLineWrap(true);
        txt_texto.setRows(5);
        txt_texto.setWrapStyleWord(true);
        txt_texto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(txt_texto);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Procesar");
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_longitud.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_longitud.setText("Longitud del texto ");

        lbl_totalpalabras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_totalpalabras.setText("Total de Palabras");

        lbl_primerletra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_primerletra.setText("Primer letra del texto");

        lbl_ultimaletra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ultimaletra.setText("Última letra del texto");

        lbl_letracentro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_letracentro.setText("Letra central del texto");

        lbl_primerpalabra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_primerpalabra.setText("Primera palabra");

        lbl_palabracentral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_palabracentral.setText("Palabra central");

        lbl_ultimapalabra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ultimapalabra.setText("Última palabra");

        lbl_repeticionesA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repeticionesA.setText("Repeticiones de \"A\", \"a\" ó \"á\"");

        lbl_repeticionesE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repeticionesE.setText("Repeticiones de \"E\", \"e\" ó \"é\"");

        lbl_repeticionesI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repeticionesI.setText("Repeticiones de \"I\", \"i\" ó \"í\"");

        lbl_repeticionesO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repeticionesO.setText("Repeticiones de \"O\", \"o\" ó \"ó\"");

        lbl_repeticionesU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repeticionesU.setText("Repeticiones de \"U\", \"u\" ó \"ú\"");

        lbl_palabrapar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_palabrapar.setText("Palabra con cantidad de caracteres par");

        lbl_palabraimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_palabraimpar.setText("Palabra con cantidad de caracteres impar");

        txt_longitud.setEnabled(false);
        txt_longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_longitudActionPerformed(evt);
            }
        });

        txt_totalpalabras.setEnabled(false);
        txt_totalpalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalpalabrasActionPerformed(evt);
            }
        });

        txt_primerletra.setEnabled(false);
        txt_primerletra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_primerletraActionPerformed(evt);
            }
        });

        txt_ultimaletra.setEnabled(false);
        txt_ultimaletra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ultimaletraActionPerformed(evt);
            }
        });

        txt_letracentral.setEnabled(false);
        txt_letracentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_letracentralActionPerformed(evt);
            }
        });

        txt_primerpalabra.setEnabled(false);
        txt_primerpalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_primerpalabraActionPerformed(evt);
            }
        });

        txt_palabracentral.setEnabled(false);
        txt_palabracentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_palabracentralActionPerformed(evt);
            }
        });

        txt_ultimapalabra.setEnabled(false);
        txt_ultimapalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ultimapalabraActionPerformed(evt);
            }
        });

        txt_repeticionesA.setEnabled(false);
        txt_repeticionesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repeticionesAActionPerformed(evt);
            }
        });

        txt_repeticionesE.setEnabled(false);
        txt_repeticionesE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repeticionesEActionPerformed(evt);
            }
        });

        txt_repeticionesI.setEnabled(false);
        txt_repeticionesI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repeticionesIActionPerformed(evt);
            }
        });

        txt_repetiionesO.setEnabled(false);
        txt_repetiionesO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repetiionesOActionPerformed(evt);
            }
        });

        txt_repeticionesU.setEnabled(false);
        txt_repeticionesU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repeticionesUActionPerformed(evt);
            }
        });

        txt_palabrapar.setEnabled(false);
        txt_palabrapar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_palabraparActionPerformed(evt);
            }
        });

        txt_palabraimpar.setEnabled(false);
        txt_palabraimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_palabraimparActionPerformed(evt);
            }
        });

        txt_traduccionMurcielago.setEditable(false);
        txt_traduccionMurcielago.setColumns(20);
        txt_traduccionMurcielago.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txt_traduccionMurcielago.setLineWrap(true);
        txt_traduccionMurcielago.setRows(5);
        txt_traduccionMurcielago.setWrapStyleWord(true);
        txt_traduccionMurcielago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txt_traduccionMurcielago);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setText("CLAVE MURCIELAGO ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_primerletra)
                    .addComponent(lbl_totalpalabras)
                    .addComponent(lbl_ultimaletra)
                    .addComponent(lbl_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_letracentro)
                    .addComponent(lbl_primerpalabra)
                    .addComponent(lbl_palabracentral)
                    .addComponent(lbl_ultimapalabra))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_repeticionesI, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_repeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_repeticionesO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_repeticionesU, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_palabraimpar)
                            .addComponent(lbl_palabrapar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_repeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repetiionesO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_repeticionesU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_palabrapar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_palabraimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_ultimapalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txt_palabracentral)
                            .addComponent(txt_primerpalabra)
                            .addComponent(txt_letracentral)
                            .addComponent(txt_longitud, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_totalpalabras, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_primerletra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ultimaletra, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(106, 106, 106)
                        .addComponent(lbl_repeticionesA)
                        .addGap(24, 24, 24)
                        .addComponent(txt_repeticionesA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_repeticionesA)
                    .addComponent(txt_repeticionesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_longitud))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_repeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_repeticionesE)
                    .addComponent(txt_totalpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_totalpalabras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_repeticionesI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_repeticionesI)
                    .addComponent(txt_primerletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_primerletra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_repetiionesO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_repeticionesO)
                    .addComponent(txt_ultimaletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ultimaletra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_repeticionesU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_repeticionesU)
                    .addComponent(txt_letracentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_letracentro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_palabrapar)
                    .addComponent(txt_palabrapar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_primerpalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_primerpalabra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_palabraimpar)
                    .addComponent(txt_palabraimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_palabracentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_palabracentral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ultimapalabra)
                    .addComponent(txt_ultimapalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Archivo");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Abrir");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Guardar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Guardar como");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jCheckBoxMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Copiar");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Cortar");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("Pegar");
        jCheckBoxMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem6);

        jCheckBoxMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Buscar");
        jCheckBoxMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Reemplazar");
        jCheckBoxMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  public String murcielagoEncode(String text) {
        String encodedText = txt_texto.getText();
        String Result = "";
        for (char c : text.toCharArray()) {
            switch (Character.toLowerCase(c)) {
                case 'm':
                    Result += "0";
                    break;
                case 'u':
                    Result += "1";
                    break;
                case 'r':
                    Result += "2";
                    break;
                case 'c':
                    Result += "3";
                    break;
                case 'i':
                    Result += "4";
                    break;
                case 'e':
                    Result += "5";
                    break;
                case 'l':
                    Result += "6";
                    break;
                case 'a':
                    Result += "7";
                    break;
                case 'g':
                    Result += "8";
                    break;
                case 'o':
                    Result += "9";
                    break;
                default:
                    Result += c;
            }
        }
        return Result;
    }
    
    
    public void LogitudTexto(){ 
    int longitud = txt_texto.getText().length();
        txt_longitud.setText(Integer.toString(longitud));
    }
    
    public void TotalPalabras(){
        
            String palabras = txt_texto.getText().trim(); 
                String[] words = palabras.split("\\s+"); 

                int wordCount = words.length;

                if (wordCount > 0 && words[0].isEmpty()) {
                    wordCount--;
                }
                
        txt_totalpalabras.setText(Integer.toString(wordCount));
        
    }
    
    public void PrimerLetra(){
        
        String text = txt_texto.getText().trim();
        char firstLetter = text.charAt(0);
        txt_primerletra.setText(Character.toString(firstLetter));
    }
    
    public void UltimaLetra(){
        
        String text = txt_texto.getText().trim(); 
        char lastLetter = text.charAt(text.length() - 1);
        txt_ultimaletra.setText(Character.toString(lastLetter));
        
        
    }
    
    public void LetraCentral(){
        
        String text = txt_texto.getText().trim();

        int length = text.length();
        int midIndex = length / 2;

        char centralLetter;
        if (length % 2 == 0) {
 
            centralLetter = text.charAt(midIndex - 1);
        } else {

            centralLetter = text.charAt(midIndex);
        }
        
        txt_letracentral.setText(Character.toString(centralLetter));
        
    }
    
    public void PrimeraPalabra(){
        
        String text = txt_texto.getText().trim(); 

        String[] words = text.split("\\s+"); 

        if (words.length > 0) {
            String firstWord = words[0];
            txt_primerpalabra.setText(firstWord); 
        }
              
    }
    
    
    public void PalabraCentral (){
        
        String text = txt_texto.getText().trim(); 

                    String[] words = text.split("\\s+"); // Dividir el texto en palabras utilizando espacios en blanco como delimitadores
                    int wordCount = words.length;

                    if (wordCount > 0) {
                        int midIndex = wordCount / 2;

                        String centralWord;
                        if (wordCount % 2 == 0) {
                            // Cantidad par de palabras, elegir la primera palabra del centro
                            centralWord = words[midIndex - 1];
                        } else {
                            // Cantidad impar de palabras, hay una única palabra en el centro
                            centralWord = words[midIndex];
                        }
                        txt_palabracentral.setText(centralWord);
                    }
                    
    }
    
    
    public void UltimaPalabra (){
        
        String text = txt_texto.getText().trim(); 

                    String[] words = text.split("\\s+"); 
                    int wordCount = words.length;

                    if (wordCount > 0) {
                        String lastWord = words[wordCount - 1]; 
                        txt_ultimapalabra.setText(lastWord);
                    }               
    }
    
    public void RepetirA (){
        
        String text = txt_texto.getText();

                int letraA = 0;
                int letra_a = 0;
                int letraAcento = 0;

                for (int i = 0; i < text.length(); i++) {
                    char currentChar = text.charAt(i);

                    if (currentChar == 'A') {
                        letraA++;
                    } else if (currentChar == 'a') {
                        letra_a++;
                    } else if (currentChar == 'á') {
                        letraAcento++;
                    }
                }
                 txt_repeticionesA.setText("A: " + Integer.toString(letraA) + ", " + "a: " + Integer.toString(letra_a) + ", "  + "á: " + Integer.toString(letraAcento));
            }
        
    
    public void RepetirE (){
        
        String text = txt_texto.getText();

                int letraE = 0;
                int letra_e = 0;
                int letraAcento = 0;

                for (int i = 0; i < text.length(); i++) {
                    char currentChar = text.charAt(i);

                    if (currentChar == 'E') {
                        letraE++;
                    } else if (currentChar == 'e') {
                        letra_e++;
                    } else if (currentChar == 'é') {
                        letraAcento++;
                    }
                }
                 txt_repeticionesE.setText("E: " + Integer.toString(letraE) + ", " + "e: " + Integer.toString(letra_e) + ", "  + "é: " + Integer.toString(letraAcento));
            }
    
            
        public void RepetirI (){
        
        String text = txt_texto.getText();

                int letraI = 0;
                int letra_i = 0;
                int letraAcento = 0;

                for (int i = 0; i < text.length(); i++) {
                    char currentChar = text.charAt(i);

                    if (currentChar == 'I') {
                        letraI++;
                    } else if (currentChar == 'i') {
                        letra_i++;
                    } else if (currentChar == 'í') {
                        letraAcento++;
                    }
                }
                 txt_repeticionesI.setText("I: " + Integer.toString(letraI) + ", " + "i: " + Integer.toString(letra_i) + ", "  + "í: " + Integer.toString(letraAcento));
            }
    
                
        public void RepetirO (){
        
        String text = txt_texto.getText();

                int letraO = 0;
                int letra_o = 0;
                int letraAcento = 0;

                for (int i = 0; i < text.length(); i++) {
                    char currentChar = text.charAt(i);

                    if (currentChar == 'O') {
                        letraO++;
                    } else if (currentChar == 'o') {
                        letra_o++;
                    } else if (currentChar == 'ó') {
                        letraAcento++;
                    }
                }
                 txt_repetiionesO.setText("O: " + Integer.toString(letraO) + ", " + "o: " + Integer.toString(letra_o) + ", "  + "ó: " + Integer.toString(letraAcento));
            }
        
        
       public void RepetirU (){
        
        String text = txt_texto.getText();

                int letraU = 0;
                int letra_u = 0;
                int letraAcento = 0;

                for (int i = 0; i < text.length(); i++) {
                    char currentChar = text.charAt(i);

                    if (currentChar == 'U') {
                        letraU++;
                    } else if (currentChar == 'u') {
                        letra_u++;
                    } else if (currentChar == 'ú') {
                        letraAcento++;
                    }
                }
                 txt_repeticionesU.setText("U: " + Integer.toString(letraU) + ", " + "u: " + Integer.toString(letra_u) + ", "  + "ú: " + Integer.toString(letraAcento));
            }
       
       
       public void PalabrasPar (){
           
            String text = txt_texto.getText().trim(); 

            
                    String[] words = text.split("\\s+");

                    List<String> evenLengthWords = new ArrayList<>();
                    for (String word : words) {
                        if (word.length() % 2 == 0) {
                            evenLengthWords.add(word);
                        }
                    }
           
                    txt_palabrapar.setText(evenLengthWords.toString());

       } 
       
         public void PalabrasInpar(){
             
             
             String text = txt_texto.getText().trim(); 

                    String[] words = text.split("\\s+"); 

                    List<String> oddLengthWords = new ArrayList<>();
                    for (String word : words) {
                        if (word.length() % 2 != 0) { // Verificar si la longitud de la palabra es impar
                            oddLengthWords.add(word);
                        }
                    }
                    
                    txt_palabraimpar.setText(oddLengthWords.toString());
             
         }
    
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
String ruta_archivo = "";

            //Boton abrir
        
       JFileChooser chooser = new JFileChooser();
    chooser.setMultiSelectionEnabled(true);
    FileNameExtensionFilter fi = new FileNameExtensionFilter("txt", "txt");
    chooser.setFileFilter(fi);
    int se = chooser.showOpenDialog(this);
    if (se == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile();
        try {
            String content = new String(Files.readAllBytes(archivo.toPath()));
            txt_texto.setText(content);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "No seleccionó ningún archivo.");
    
        }    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    
    
    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed


        
   

           
           
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem6ActionPerformed
 // Acción del botón "Pegar"
    txt_texto.paste();
    }//GEN-LAST:event_jCheckBoxMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String inputText = txt_texto.getText();
    String encodedText = murcielagoEncode(inputText);
    
    // Imprimir en consola para depuración
    System.out.println("Texto original: " + inputText);
    System.out.println("Texto codificado: " + encodedText);
    
    // Establecer el texto codificado en la interfaz
    txt_traduccionMurcielago.setText(encodedText);  
    
        LogitudTexto();
        
        TotalPalabras();
        
        PrimerLetra();
        
        UltimaLetra();
        
        LetraCentral();
        
        PrimeraPalabra();
        
        PalabraCentral();
        
        UltimaPalabra();
        
        RepetirA();
        
        RepetirE();
        
        RepetirI();
        
        RepetirO();
        
        RepetirU();
        
        PalabrasPar();
        
        PalabrasInpar();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
 // Acción del botón "Guardar como"
    JFileChooser chooser = new JFileChooser();
    int option = chooser.showSaveDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
        File fileToSave = chooser.getSelectedFile();
        String filePath = fileToSave.getAbsolutePath();
        
        if (!filePath.toLowerCase().endsWith(".txt")) {
            filePath += ".txt";
        }
        
        System.out.println("esto trae la ruta: " + filePath);
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
            writer.write(txt_texto.getText());
            JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       } 
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
    // Acción del botón "Copiar"
    txt_texto.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
        // TODO add your handling code here:
         // Acción del botón "Cortar"
    txt_texto.cut();
    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void jCheckBoxMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem8ActionPerformed
 // Acción del botón "Reemplazar"
    String searchStr = JOptionPane.showInputDialog(this, "Buscar:");
    if (searchStr != null) {
        String replaceStr = JOptionPane.showInputDialog(this, "Reemplazar con:");
        if (replaceStr != null) {
            String text = txt_texto.getText();
            String newText = text.replace(searchStr, replaceStr);
            txt_texto.setText(newText);
        }  
                }       
    }//GEN-LAST:event_jCheckBoxMenuItem8ActionPerformed

    private void jCheckBoxMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem7ActionPerformed
        // TODO add your handling code here:
        
    // Acción del botón "Buscar"
    String searchStr = JOptionPane.showInputDialog(this, "Buscar:");
    if (searchStr != null) {
        String text = txt_texto.getText();
        int startIndex = text.indexOf(searchStr);
        if (startIndex != -1) {
            int endIndex = startIndex + searchStr.length();
            txt_texto.setSelectionStart(startIndex);
            txt_texto.setSelectionEnd(endIndex);
        } else {
            JOptionPane.showMessageDialog(this, "Texto no encontrado.");
        }
    }
    }//GEN-LAST:event_jCheckBoxMenuItem7ActionPerformed

    private void txt_longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_longitudActionPerformed
        
       
        
    }//GEN-LAST:event_txt_longitudActionPerformed

    private void txt_totalpalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalpalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalpalabrasActionPerformed

    private void txt_primerletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_primerletraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_primerletraActionPerformed

    private void txt_ultimaletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ultimaletraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ultimaletraActionPerformed

    private void txt_letracentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_letracentralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_letracentralActionPerformed

    private void txt_primerpalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_primerpalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_primerpalabraActionPerformed

    private void txt_palabracentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_palabracentralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_palabracentralActionPerformed

    private void txt_ultimapalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ultimapalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ultimapalabraActionPerformed

    private void txt_repeticionesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repeticionesAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repeticionesAActionPerformed

    private void txt_repeticionesEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repeticionesEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repeticionesEActionPerformed

    private void txt_repeticionesIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repeticionesIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repeticionesIActionPerformed

    private void txt_repetiionesOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repetiionesOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repetiionesOActionPerformed

    private void txt_repeticionesUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repeticionesUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repeticionesUActionPerformed

    private void txt_palabraparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_palabraparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_palabraparActionPerformed

    private void txt_palabraimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_palabraimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_palabraimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Vista1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_letracentro;
    private javax.swing.JLabel lbl_longitud;
    private javax.swing.JLabel lbl_palabracentral;
    private javax.swing.JLabel lbl_palabraimpar;
    private javax.swing.JLabel lbl_palabrapar;
    private javax.swing.JLabel lbl_primerletra;
    private javax.swing.JLabel lbl_primerpalabra;
    private javax.swing.JLabel lbl_repeticionesA;
    private javax.swing.JLabel lbl_repeticionesE;
    private javax.swing.JLabel lbl_repeticionesI;
    private javax.swing.JLabel lbl_repeticionesO;
    private javax.swing.JLabel lbl_repeticionesU;
    private javax.swing.JLabel lbl_totalpalabras;
    private javax.swing.JLabel lbl_ultimaletra;
    private javax.swing.JLabel lbl_ultimapalabra;
    private javax.swing.JTextField txt_letracentral;
    private javax.swing.JTextField txt_longitud;
    private javax.swing.JTextField txt_palabracentral;
    private javax.swing.JTextField txt_palabraimpar;
    private javax.swing.JTextField txt_palabrapar;
    private javax.swing.JTextField txt_primerletra;
    private javax.swing.JTextField txt_primerpalabra;
    private javax.swing.JTextField txt_repeticionesA;
    private javax.swing.JTextField txt_repeticionesE;
    private javax.swing.JTextField txt_repeticionesI;
    private javax.swing.JTextField txt_repeticionesU;
    private javax.swing.JTextField txt_repetiionesO;
    private javax.swing.JTextArea txt_texto;
    private javax.swing.JTextField txt_totalpalabras;
    private javax.swing.JTextArea txt_traduccionMurcielago;
    private javax.swing.JTextField txt_ultimaletra;
    private javax.swing.JTextField txt_ultimapalabra;
    // End of variables declaration//GEN-END:variables

    private void guardarArchivo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
